// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            Email = "ava.stone@example.com",
                            Name = "Ava Stone"
                        },
                        new
                        {
                            Id = 2,
                            Country = "UK",
                            Email = "liam.brooks@example.com",
                            Name = "Liam Brooks"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Italy",
                            Email = "sofia.rossi@example.com",
                            Name = "Sofia Rossi"
                        });
                });

            modelBuilder.Entity("Domain.Entities.DSP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("DSPs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Spotify"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Apple Music"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Amazon Music"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ISRC")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("ISRC")
                        .IsUnique();

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            Genre = "Pop",
                            ISRC = "USRC17600001",
                            ReleaseDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Distributed",
                            Title = "Midnight Drive"
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 1,
                            Genre = "Pop",
                            ISRC = "USRC17600002",
                            ReleaseDate = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Submitted",
                            Title = "Golden Hour"
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 1,
                            Genre = "Electronic",
                            ISRC = "USRC17600003",
                            ReleaseDate = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Draft",
                            Title = "Neon Skyline"
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 2,
                            Genre = "Rock",
                            ISRC = "GBRC17600004",
                            ReleaseDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Distributed",
                            Title = "Silver Rain"
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 2,
                            Genre = "Rock",
                            ISRC = "GBRC17600005",
                            ReleaseDate = new DateTime(2025, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Draft",
                            Title = "Broken Compass"
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 2,
                            Genre = "Indie",
                            ISRC = "GBRC17600006",
                            ReleaseDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Submitted",
                            Title = "Paper Boats"
                        },
                        new
                        {
                            Id = 7,
                            ArtistId = 3,
                            Genre = "Jazz",
                            ISRC = "ITRC17600007",
                            ReleaseDate = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Draft",
                            Title = "Luna Nera"
                        },
                        new
                        {
                            Id = 8,
                            ArtistId = 3,
                            Genre = "Jazz",
                            ISRC = "ITRC17600008",
                            ReleaseDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Distributed",
                            Title = "Vento del Sud"
                        });
                });

            modelBuilder.Entity("Domain.Entities.TrackDistribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DSPId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DSPId");

                    b.HasIndex("TrackId", "DSPId")
                        .IsUnique();

                    b.ToTable("TrackDistributions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DSPId = 1,
                            Status = "Live",
                            SubmittedAt = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrackId = 1
                        },
                        new
                        {
                            Id = 2,
                            DSPId = 2,
                            Status = "Live",
                            SubmittedAt = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrackId = 1
                        },
                        new
                        {
                            Id = 3,
                            DSPId = 1,
                            Status = "Pending",
                            SubmittedAt = new DateTime(2025, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrackId = 2
                        },
                        new
                        {
                            Id = 4,
                            DSPId = 1,
                            Status = "Live",
                            SubmittedAt = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrackId = 4
                        },
                        new
                        {
                            Id = 5,
                            DSPId = 3,
                            Status = "Live",
                            SubmittedAt = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrackId = 4
                        },
                        new
                        {
                            Id = 6,
                            DSPId = 2,
                            Status = "Pending",
                            SubmittedAt = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrackId = 6
                        },
                        new
                        {
                            Id = 7,
                            DSPId = 1,
                            Status = "Live",
                            SubmittedAt = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrackId = 8
                        },
                        new
                        {
                            Id = 8,
                            DSPId = 2,
                            Status = "Live",
                            SubmittedAt = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrackId = 8
                        },
                        new
                        {
                            Id = 9,
                            DSPId = 3,
                            Status = "Rejected",
                            SubmittedAt = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrackId = 8
                        });
                });

            modelBuilder.Entity("Domain.Entities.Track", b =>
                {
                    b.HasOne("Domain.Entities.Artist", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Domain.Entities.TrackDistribution", b =>
                {
                    b.HasOne("Domain.Entities.DSP", "DSP")
                        .WithMany("TrackDistributions")
                        .HasForeignKey("DSPId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Track", "Track")
                        .WithMany("TrackDistributions")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DSP");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Domain.Entities.Artist", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Domain.Entities.DSP", b =>
                {
                    b.Navigation("TrackDistributions");
                });

            modelBuilder.Entity("Domain.Entities.Track", b =>
                {
                    b.Navigation("TrackDistributions");
                });
#pragma warning restore 612, 618
        }
    }
}
