@Track_Management_HostAddress = http://localhost:5101

GET {{Track_Management_HostAddress}}/api/artists
Accept: application/json

###

GET {{Track_Management_HostAddress}}/api/tracks
Accept: application/json

###
